#ifndef MONOMI_CHARACTER_TECHNIQUE_FLAG_HPP
#define MONOMI_CHARACTER_TECHNIQUE_FLAG_HPP

#include <bitset>

namespace monomi {
    enum CharacterTechniqueFlag {
        CHARACTER_DOUBLE_JUMP_TECHNIQUE,
        CHARACTER_GLIDE_TECHNIQUE,
        CHARACTER_SLIDE_TECHNIQUE,
        CHARACTER_STOMP_TECHNIQUE,
        CHARACTER_TELEPORT_TECHNIQUE,
        CHARACTER_TRIPLE_JUMP_TECHNIQUE,
        CHARACTER_WALL_JUMP_TECHNIQUE,
        CHARACTER_WALL_RUN_TECHNIQUE,
        CHARACTER_WALL_SLIDE_TECHNIQUE,

        CHARACTER_TECHNIQUE_COUNT
    };

    typedef std::bitset<CHARACTER_TECHNIQUE_COUNT> CharacterTechniqueFlagSet;
}

#endif // MONOMI_CHARACTER_TECHNIQUE_FLAG_HPP
